server:
  port: 8082

spring:
  application:
    name: 'medical-folder'
  datasource:
    url: jdbc:h2:file:./data/medical-folder   # file-based DB, stored locally
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update                 # sync db without dropping
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka